### ISSUE TITLE
More GraphQL ( for FE )

### ISSUE THREAD

**Issue by nware1066** [never-alone-turing/FE#40]
This tutorial seems to have some pretty good info on the basic setup for Apollo/graphQL with React Native:
https://hasura.io/learn/graphql/react-native/apollo-client/

This is just for a regular react app, but it might still be useful:
https://www.howtographql.com/react-apollo/1-getting-started/

**Comment by holladayian** [comment]
I put this in the project board, as a card instead of an issue, so I'll remove it from here as an issue.
